version: '3'
services:
  financia-pro:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/financia-pro
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVICE_NAME: financia-pro

  db:
    image: mysql:8.0
    container_name: financia-pro-mysql
    restart: unless-stopped
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: financia-pro
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: elestio/nginx-auto-ssl
    container_name: financia-pro-nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - financia-pro
    environment:
      DOMAINS: '159.203.111.15'  # Cambia 'localhost' por la IP del servidor si es necesario

volumes:
  dbdata:
    driver: local
